### PR TITLE
New camera button

### PR DESCRIPTION
**Pull request by RoundDev**
@fdlane @mhvolk @donaldnash1989 @amberolive @KeithClinard @zachnthebox

### CODE REVIEW

**Comment by RoundDev** [comment]
@amberolive  it was customized icon per Donald request.

**Comment by amberolive** [comment]
@RoundDev I was suggesting to delete `camera_icon.png` but keep the one we are using with is `camera_icon_white.png`.

**Comment by zachnthebox** [comment]
It might be better to use icon fonts instead of using actually png's images. Icon fonts give you scalable icons that can instantly be customized — size, color, drop shadow, and anything that can be done with the power of CSS. We'll talk more about it on Monday.
[Font Awesome](http://fontawesome.io/) is an icon font css library that we have used internally for our bootstrap web apps if you wanted to look into it before we meet.

**Comment by zachnthebox** [comment]
Closed for upcoming PR

**Pull request closed without merging**
